import {
  ArrowRightLeft,
  Award,
  BarChart3,
  BellRing,
  Bitcoin,
  Briefcase,
  Building2,
  CalendarDays,
  ChartLine,
  ClipboardCheck,
  Code2,
  CreditCard,
  Database,
  DoorOpen,
  Eye,
  FileText,
  Gauge,
  Globe,
  Handshake,
  Headphones,
  HeartHandshake,
  Languages,
  Layers,
  LifeBuoy,
  Lightbulb,
  Link2,
  Lock,
  Mail,
  MessageCircle,
  Monitor,
  Network,
  Paintbrush,
  PenTool,
  Percent,
  PlugZap,
  Repeat,
  Rocket,
  Route,
  Scale,
  Search,
  Server,
  Settings2,
  Shield,
  Smartphone,
  Sparkles,
  Target,
  TrendingUp,
  Trophy,
  Users,
  Wallet,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const iconMap = {
  layers: Layers,
  trophy: Trophy,
  chart: BarChart3,
  chartLine: ChartLine,
  bitcoin: Bitcoin,
  code: Code2,
  monitor: Monitor,
  users: Users,
  door: DoorOpen,
  network: Network,
  shield: Shield,
  repeat: Repeat,
  handshake: Handshake,
  creditcard: CreditCard,
  smartphone: Smartphone,
  headphones: Headphones,
  server: Server,
  gauge: Gauge,
  globe: Globe,
  zap: Zap,
  settings: Settings2,
  lock: Lock,
  rocket: Rocket,
  clipboard: ClipboardCheck,
  paintbrush: Paintbrush,
  plug: PlugZap,
  lifebuoy: LifeBuoy,
  mail: Mail,
  message: MessageCircle,
  briefcase: Briefcase,
  building: Building2,
  trending: TrendingUp,
  wallet: Wallet,
  filetext: FileText,
  sparkles: Sparkles,
  eye: Eye,
  scale: Scale,
  heart: HeartHandshake,
  lightbulb: Lightbulb,
  target: Target,
  route: Route,
  database: Database,
  bell: BellRing,
  search: Search,
  pen: PenTool,
  wrench: Wrench,
  migrate: ArrowRightLeft,
  languages: Languages,
  calendar: CalendarDays,
  percent: Percent,
  award: Award,
  link: Link2,
} satisfies Record<string, LucideIcon>;

export type IconKey = keyof typeof iconMap;

export function getIcon(name?: string): LucideIcon {
  if (name && name in iconMap) return iconMap[name as IconKey];
  return Sparkles;
}
